foodbot:
  default-placeholders:
    greeting:
      key: MORNING_GREETING
      icon: sun
      description: Random greeting message
    main-course:
      key: MEAL_MAIN_COURSE
      icon: food
      description: Main course of the day
    salad:
      key: MEAL_SALAD
      icon: salad
      description: Salad of the day
  scheduling:
    menu-notification-schedule: 0 0 9 * * *
    menu-update-check-schedule: 0 0 * * * SUN,MON
  messaging:
    username: <SKYPE USERNAME>
    password: <SKYPE PASSWORD>
    group-id: <SKYPE GROUP ID>
    shorter-token-lifespan: true
  notifications:
    expected-subject: <EXPECTED EMAIL SUBJECT>
    whitelisted-senders:
      - <WHITELISTED SENDER EMAIL>
      - <WHITELISTED SENDER EMAIL>
      - ...
    menu-reviewers:
      - <REVIEWER EMAIL ADDRESS>
      - <REVIEWER EMAIL ADDRESS>
      - ...
    pop3:
      host: pop.gmail.com
      port: 995
      username: <POP3 SERVER USERNAME>
      password: <POP3 SERVER PASSWORD>
    smtp:
      host: smtp.gmail.com
      port: 465
      username: <SMTP SERVER USERNAME>
      password: <SMTP SERVER PASSWORD>
      display-name: FoodBot
    csv:
      separator: ;
spring:
  h2:
    console:
      enabled: true
#  Alternatively, you can use a persistent database, like MariaDB
#  datasource:
#    url: jdbc:mariadb://<MARIADB SERVER>:<MARIADB PORT>/<DATABASE NAME>
#    username: <MARIADB USERNAME>
#    password: <MARIADB PASSWORD>
#    driver-class-name: org.mariadb.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#      generate-ddl: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MariaDB103Dialect
  profiles:
    active: development
